spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deanoffice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
#    connection-timeout: 60000
#    maximum-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  http:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jackson:
    time-zone: Europe/Minsk
flyway:
  baseline-on-migrate: true

#  hibernate:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    show_sql: true
#    format_sql: true

server:
  port: 8080
  decimal-point: ","
swagger:
  host: localhost:8080

faculty:
  foreign:
    id: 8

security:
  secret: SecretKe487563465347
# 5 days
  expiration-time: 432_000
# 1 year
#  expiration-time: 31_536_000
  token-prefix: Bearer
  header-string: Authorization
